# Generated by Django 2.0.1 on 2018-01-12 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('incomodo', models.IntegerField()),
                ('interesse1', models.IntegerField()),
                ('interesse2', models.IntegerField()),
                ('num_sessao', models.IntegerField()),
                ('num_video_preferido', models.IntegerField()),
                ('justificativa', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
