# Generated by Django 2.0.1 on 2018-01-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='text',
            new_name='justificativa',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='author',
            new_name='nome',
        ),
    ]
