# Generated by Django 2.0.1 on 2018-01-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='incomodo',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='interesse1',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='interesse2',
        ),
    ]
