# Generated by Django 2.0.1 on 2018-01-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0002_auto_20180112_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='incomodo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='interesse1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='interesse2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
