# Generated by Django 2.0.1 on 2018-01-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0003_auto_20180112_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='nome',
        ),
    ]
