# Generated by Django 2.0.1 on 2018-02-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0005_auto_20180120_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
    ]
