# Generated by Django 2.0.1 on 2018-02-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0008_auto_20180227_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
