# Generated by Django 2.0.1 on 2018-02-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0009_auto_20180227_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
