# Generated by Django 2.0.1 on 2018-02-27 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0012_auto_20180227_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='num_video_preferido',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
