# Generated by Django 2.0.1 on 2018-02-27 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0013_auto_20180227_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='num_video_preferido',
            field=models.IntegerField(choices=[(1, 'Primeiro'), (2, 'Segundo')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
