# Generated by Django 2.0.1 on 2018-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0015_stressfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='justificativa',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stressfeedback',
            name='justificativa',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stressfeedback',
            name='rebuff_feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stressfeedback',
            name='recommend_feedback',
            field=models.TextField(default=''),
        ),
    ]
