# Generated by Django 2.0.1 on 2018-03-19 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0016_auto_20180317_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='num_video_preferido',
            field=models.IntegerField(choices=[(1, 'Primeiro'), (2, 'Segundo'), (0, 'Nenhum')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='stressfeedback',
            name='justificativa',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='stressfeedback',
            name='rebuff_feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='stressfeedback',
            name='recommend_feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
