# Generated by Django 2.0.1 on 2018-06-12 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0017_auto_20180319_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='english',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='num_video_preferido',
            field=models.IntegerField(choices=[(1, 'Primeiro/First'), (2, 'Segundo/Second'), (0, 'Nenhum/None')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
