# Generated by Django 2.0.1 on 2018-06-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0019_feedback_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressfeedback',
            name='session_id',
            field=models.CharField(default='', max_length=40, verbose_name='Chave sessão'),
        ),
    ]
