# Generated by Django 2.0.7 on 2018-08-01 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0028_auto_20180716_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='num_video_preferido',
            field=models.IntegerField(choices=[(1, 'Primeiro/First'), (2, 'Segundo/Second'), (0, 'Nenhum/None')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
