# Generated by Django 2.0.6 on 2018-08-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0029_auto_20180801_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='email',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
