# Generated by Django 2.0.6 on 2018-08-23 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_sessions', '0031_auto_20180823_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='num_video_preferido',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
